# Generated by Django 4.1.2 on 2022-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="orders",
            field=models.ManyToManyField(related_name="books", to="orders.order"),
        ),
    ]
